import type { Config } from '@shared/types'
import { DEFAULT_BINDINGS } from '@shared/types'
import { CarType, HandDriveType, MicType, PhoneWorkMode } from '@shared/types/Config'

export const DEFAULT_CONFIG: Config = {
  projectionWidth: 800,
  projectionHeight: 800,
  projectionFps: 45,
  projectionDpi: 140,
  projectionViewAreaTop: 118,
  projectionViewAreaBottom: 118,
  projectionViewAreaLeft: 118,
  projectionViewAreaRight: 118,
  projectionSafeAreaTop: 0,
  projectionSafeAreaBottom: 0,
  projectionSafeAreaLeft: 0,
  projectionSafeAreaRight: 0,
  projectionSafeAreaDrawOutside: false,
  clusterWidth: 1280,
  clusterHeight: 720,
  clusterFps: 60,
  clusterDpi: 0,
  clusterViewAreaTop: 0,
  clusterViewAreaBottom: 0,
  clusterViewAreaLeft: 0,
  clusterViewAreaRight: 0,
  clusterSafeAreaTop: 60,
  clusterSafeAreaBottom: 10,
  clusterSafeAreaLeft: 300,
  clusterSafeAreaRight: 300,
  lastConnectedAaBtMac: '',
  lastPhoneWorkMode: PhoneWorkMode.CarPlay,
  apkVer: '2025.03.19.1126',
  carName: 'motoCarPlay',
  oemName: 'BMW R75/6',
  darkMode: true,
  nightMode: true,
  hand: HandDriveType.LHD,
  mediaDelay: 500,
  samplingFrequency: 1,
  callQuality: 1,
  autoConn: true,
  UseBTPhone: false,
  disableAudioOutput: true,
  dashboardMediaInfo: false,
  dashboardVehicleInfo: true,
  dashboardRouteInfo: true,
  gps: false,
  gnssGps: false,
  gnssGlonass: false,
  gnssGalileo: false,
  gnssBeiDou: false,
  wifiType: '5ghz',
  wifiChannel: 36,
  micType: MicType.CarMic,
  phoneConfig: {
    3: { frameInterval: 5000 },
    5: { frameInterval: null }
  },
  carType: CarType.Gasoline,
  evConnectorTypes: [],
  wirelessAaEnabled: false,
  wirelessCpEnabled: false,
  connectionPreference: 'dongle',
  wifiPassword: '12345678',
  btAdapter: 'hci0',
  wifiInterface: 'wlan0',
  appearanceMode: 'auto',
  startPage: 'home',
  language: 'en',
  kiosk: { main: true, dash: false, aux: false },
  uiZoomPercent: 100,
  cameraId: '',
  camera: { main: false, dash: false, aux: false },
  cameraMirror: false,
  autoSwitchOnStream: false,
  autoSwitchOnPhoneCall: false,
  autoSwitchOnGuidance: false,
  autoSwitchOnReverse: false,
  dongleToolsIp: '',
  visualAudioDelayMs: 120,
  audioVolume: 1,
  navVolume: 0.5,
  voiceAssistantVolume: 0.5,
  callVolume: 0.5,
  systemSoundsVolume: 0.75,
  audioOutputDevice: '',
  audioOutputDeviceLabel: '',
  audioInputDevice: '',
  audioInputDeviceLabel: '',
  primaryColorDark: '',
  highlightColorDark: '',
  primaryColorLight: '',
  highlightColorLight: '',
  backgroundColorDark: '',
  backgroundColorLight: '',
  mainScreenWidth: 800,
  mainScreenHeight: 800,
  dashScreenActive: false,
  dashScreenWidth: 1280,
  dashScreenHeight: 720,
  auxScreenActive: false,
  auxScreenWidth: 800,
  auxScreenHeight: 480,
  mainScreenBounds: { x: 0, y: 0, width: 0, height: 0 },
  dashScreenBounds: { x: 0, y: 0, width: 0, height: 0 },
  auxScreenBounds: { x: 0, y: 0, width: 0, height: 0 },
  dashboards: {
    dash1: { main: false, dash: false, aux: false, pos: 1 },
    dash2: { main: false, dash: false, aux: false, pos: 2 },
    dash3: { main: false, dash: false, aux: false, pos: 3 },
    dash4: { main: false, dash: false, aux: false, pos: 4 }
  },
  media: { main: false, dash: false, aux: false },
  bindings: DEFAULT_BINDINGS,
  dongleIcon120: '',
  dongleIcon180: '',
  dongleIcon256: ''
}
